### PR TITLE
Merge Navigation Management Review - Meeds-io/MIPs#137

### LINKED ISSUE #137: Navigation Management Review
## Rationale

As we constantly are wanting better UX consistency, we would like to improve the UX of page creation. Indeed, technical labels are used (nodes, node name) and some items can be displayed only on demand, and not by default.
Additionally, from now on, Space Hosts can access this UI to manage navigation and to create pages/nodes.

Thus, we aim to providing a UX that helps any user to create an item (node) and to associate to it a page, a link, etc only when needed.

#### UX to create an item

**Review of the UX to create an item:**
- Node ID can be customized on demand at the creation as it is currently. Once created, I cannot edit it indeed.
- Icon addition UI is reviewed
- Visibility option UI is kept as is
- Default option is "creating a new page". Users can still add a node without a page using the option "Menu Section"

**Review of the UX to attach an existing page to the item**
- Same UX as when selecting github repositories or spaces in the action creation
- Default setting: will be open in the same tab (same UX as the links portlet)

**Review of the UX to attach an external link to the item**
- Default setting: will be open in a new tab (as it is an external link)

**Review the UX to access templates list**
- List templates
- Expanded view when needed

https://youtu.be/NXEELK1H2uY

#### UX to access templates list (creation)

**Default display**
- Blank templates (grid & dynamic)
- Default templates (sorted alphabetically if not used, to study: then sorted upon latest selection): General Stream, Dashboard, Analytics, Space Stream
- If description, then this will be displayed below the name of the template as follow
image

**Custom display**
Depending on templates added by users, the list can be long. Hence, we recommend to list 2 templates (same sorting as previously explained) per category, starting by the blank and the default ones and finally the customized ones.
As we have more than 6 templates to list (2 category like default display), users can click to see more from each category to expand the drawer and view all templates

list expand

**Selection UX**

When hovering a preview, I can either preview or select the template.
When clicking to preview, I see the image full screen like any other image AND I have an option to select this template

preview

#### To study
When needed, it must be possible to browse the navigation of a space like it is for any other sites
Indeed, we can add subnode to space navigation. However, it is not possible to access it from the space menu (desktop/mobile) or from the left menu.
It needs to be studied so space hosts can create nodes and manage their navigation.

### Expected Volume & Performance

No change on data models and backend performances. 

### Security 

No change on security schema of Navigation and Pages.

### Extensibility 

N/A

### Configurability 

N/A

### Upgradability

N/A

### Existing Features

N/A

### Feature Flags

No feature flags

### Other Non Functional Requirements

N/A

### Access 
   - No major change on Rest endpoints
   - No new portlets will be added, the existing portlets of Page Templates and Navigations will be reworked to enhance UX

### PR DESCRIPTION
**Pull request by SaraBoutej**
Resolves https://github.com/Meeds-io/MIPs/issues/137

### CODE REVIEW

**Comment by rdenarie** [comment]
Hi @SaraBoutej 
There 2 of 3 sonar issues that can be fixed easily : the one with the alt of the image, and the one about the if/else organization.
Can you update that ?

Thanks

**Comment by boubaker** [comment]
> Hi @SaraBoutej There 2 of 3 sonar issues that can be fixed easily : the one with the alt of the image, and the one about the if/else organization. Can you update that ?
> 
> Thanks

Thanks @rdenarie I kept the `alt` sonar issue only to not change algorithms in this advanced stage of MIP merge. Thanks for your heads-up

**Comment by rdenarie** [comment]
Will you open an issue to fix it later ?

**Comment by boubaker** [comment]
> Will you open an issue to fix it later ?

Nope, as said

> I kept the `alt` sonar issue

so, this will be fixed here since the scope is reduced and will not affect existing features nor algorithms.

**Comment by SaraBoutej** [comment]
@boubaker @rdenarie alt text added to the image

**Comment by margondicco** [comment]
Hello my feedbacks

**1 - Must have**
some labels in english and i can't find the strings in crowdin

image

and
image

**2 - Nice to have**
select the choice "select an existing page" and search a page
=> we have some pages with the status Draft. Expectation: hide the draft page

**3 - Nice to have**
i'm not confortable with the step select a template. I didn't see the selected template. My proposal : increase border size

**4 - Nice to have**

A group node must not be clickable. Here i click on the group node and a blank page opens

image


Thank you

**Comment by rdenarie** [comment]
Ok for me, you can proceed to merge

**Review by boubaker — APPROVED** [review]

**Pull request merged**
